import Head from "next/head";
import React from "react";
import About from "./components/About";
import Contact from "./components/contact";
import Header from "./components/header";
import ProjectSlide from "./components/project-slide";
import Services from "./components/services";
import Skills from "./components/skills";
import HamburgerMenu from "./components/hamburger-menu";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <About />
      <Skills />
      <Services />
      <ProjectSlide />
      <Contact />
    </div>
  );
}
